namespace ITCreatings.Ndb.Attributes
{
    /// <summary>
    /// Marks field as PrimaryKey
    /// </summary>
    public sealed class DbPrimaryKeyFieldAttribute : DbFieldAttribute
    {
        private bool isDbGenerated = true;

        /// <summary>
        /// Determines if field is generated by database
        /// </summary>
        public bool IsDbGenerated
        {
            get
            {
                return isDbGenerated;
            }
            set
            {
                isDbGenerated = value;
            }
        }
    }
}