namespace ITCreatings.Ndb.Attributes
{
    /// <summary>
    /// Marks field as PrimaryKey
    /// </summary>
    public class DbPrimaryKeyFieldAttribute : DbFieldAttribute
    {
        /// <summary>
        /// Determines if field is generated by database
        /// </summary>
        public bool IsDbGenerated = true;
    }
}